# Generated by Django 5.1.2 on 2024-10-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_form_uuid', models.UUIDField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
